# escape=`

FROM mcr.microsoft.com/windows/nanoserver:1809 

ARG VS_REMOTE_DEBUGGER_PATH
ARG VS_OUT_DIR

ADD $VS_REMOTE_DEBUGGER_PATH "c:\windows"

WORKDIR "c:\app"
COPY .\output .

ENTRYPOINT ["IotEdgeModule1.exe"]
